name: Picassco Deployment (Canary)
on:
    push:
        branches:
            - canary
    pull_request:
        branches:
            - canary
env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_CANARY }}
jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: superfly/flyctl-actions@1.1
              with:
                  args: "deploy"
